import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {BarChart3,LayoutDashboard,PlusCircle,History,Settings,Upload,Search,TrendingUp,TrendingDown,Target,Wallet,CalendarDays,ChevronRight,Trash2,CheckCircle2,CircleDollarSign} from "lucide-react";
import "./styles.css";

const seed=[
{id:1,date:"2026-09-08",bookmaker:"Bet365",sport:"Football",games:2,selections:5,odds:5.4,stake:20,return:108,result:"Won",markets:["Match Result","Goals","Player Shots"],note:"Weekend acca builder"},
{id:2,date:"2026-09-07",bookmaker:"Sky Bet",sport:"Football",games:3,selections:6,odds:7.2,stake:15,return:0,result:"Lost",markets:["Goals","Corners","Cards"],note:""},
{id:3,date:"2026-09-05",bookmaker:"Bet365",sport:"Football",games:2,selections:4,odds:4.1,stake:10,return:41,result:"Won",markets:["Goals","BTTS"],note:""},
{id:4,date:"2026-09-02",bookmaker:"Ladbrokes",sport:"Football",games:1,selections:3,odds:3.8,stake:10,return:0,result:"Lost",markets:["Match Result","Goals"],note:""},
{id:5,date:"2026-08-29",bookmaker:"Bet365",sport:"Football",games:4,selections:8,odds:10.5,stake:10,return:0,result:"Lost",markets:["Goals","Player Shots"],note:""},
{id:6,date:"2026-08-22",bookmaker:"Sky Bet",sport:"Basketball",games:2,selections:4,odds:3.6,stake:25,return:90,result:"Won",markets:["Moneyline","Player Points"],note:""},
];

function money(n){return `£${n.toFixed(2)}`}
function App(){
 const [bets,setBets]=useState(seed),[page,setPage]=useState("Dashboard"),[query,setQuery]=useState(""),[month,setMonth]=useState("All");
 const stats=useMemo(()=>{const totalStake=bets.reduce((a,b)=>a+b.stake,0), ret=bets.reduce((a,b)=>a+b.return,0), wins=bets.filter(b=>b.result==="Won").length;return {totalStake,ret,profit:ret-totalStake,wins,losses:bets.length-wins,winRate:bets.length?wins/bets.length*100:0,avgOdds:bets.length?bets.reduce((a,b)=>a+b.odds,0)/bets.length:0,roi:totalStake?(ret-totalStake)/totalStake*100:0,bankroll:1000+ret-totalStake}},[bets]);
 const months=useMemo(()=>{let m={};bets.forEach(b=>{let k=b.date.slice(0,7);if(!m[k])m[k]={stake:0,ret:0,wins:0,bets:0};m[k].stake+=b.stake;m[k].ret+=b.return;m[k].wins+=b.result==="Won"?1:0;m[k].bets++});return Object.entries(m).sort().map(([k,v])=>({...v,k,profit:v.ret-v.stake}))},[bets]);
 const filtered=bets.filter(b=>(month==="All"||b.date.startsWith(month))&&(`${b.bookmaker} ${b.sport} ${b.markets.join(" ")} ${b.result}`).toLowerCase().includes(query.toLowerCase()));
 function addBet(){const b={id:Date.now(),date:new Date().toISOString().slice(0,10),bookmaker:"Bet365",sport:"Football",games:2,selections:4,odds:4.5,stake:10,return:0,result:"Pending",markets:["Goals","Match Result"],note:"New manually added bet"};setBets(x=>[b,...x]);setPage("History")}
 function scan(){addBet();alert("Demo scanner: a draft bet was created. In production, connect OCR/vision to extract the slip fields from the uploaded screenshot.")}
 return <div className="app">
  <aside><div className="brand"><CircleDollarSign/> <span>BET<span>TRACKER</span></span></div>
   {[[LayoutDashboard,"Dashboard"],[PlusCircle,"Add Bet"],[History,"Bet History"],[BarChart3,"Analytics"],[Settings,"Settings"]].map(([I,n])=><button className={page===n?"nav active":"nav"} onClick={()=>setPage(n)}><I size={19}/>{n}</button>)}
   <div className="sidebox"><Wallet size={20}/><small>Current bankroll</small><strong>{money(stats.bankroll)}</strong><em>{stats.profit>=0?"+":""}{money(stats.profit)} all time</em></div>
  </aside>
  <main><header><div><h1>{page}</h1><p>Track every builder, selection and result.</p></div><button className="primary" onClick={()=>setPage("Add Bet")}><PlusCircle size={18}/> Add bet</button></header>
   {page==="Dashboard"&&<Dashboard stats={stats} months={months} bets={bets} setPage={setPage}/>}
   {page==="Add Bet"&&<AddBet onAdd={addBet} onScan={scan}/>}
   {page==="Bet History"&&<HistoryPage bets={filtered} query={query} setQuery={setQuery} month={month} setMonth={setMonth} setBets={setBets}/>}
   {page==="Analytics"&&<Analytics stats={stats} bets={bets} months={months}/>}
   {page==="Settings"&&<SettingsPage/>}
  </main>
 </div>
}
function Cards({stats}){return <div className="cards">
 {[[Wallet,"Total Staked",money(stats.totalStake)], [TrendingUp,"Profit / Loss",(stats.profit>=0?"+":"")+money(stats.profit),stats.profit], [Target,"Win Rate",stats.winRate.toFixed(1)+"%"],[BarChart3,"Average Odds",stats.avgOdds.toFixed(2)],[CircleDollarSign,"ROI",(stats.roi>=0?"+":"")+stats.roi.toFixed(1)+"%"],[CalendarDays,"Total Bets",stats.wins+stats.losses]].map(([I,l,v,raw])=><div className="card"><div className="icon"><I size={18}/></div><span>{l}</span><b className={raw<0?"negative":raw>0?"positive":""}>{v}</b></div>)}
 </div>}
function Dashboard({stats,months,bets,setPage}){let max=Math.max(1,...months.map(x=>Math.abs(x.profit)));return <><Cards stats={stats}/><div className="grid2"><section className="panel"><div className="panelhead"><div><h2>Monthly profit & loss</h2><p>Net result by month</p></div><button className="ghost" onClick={()=>setPage("Analytics")}>View analytics <ChevronRight size={15}/></button></div><div className="bars">{months.map(m=><div className="barcol"><div className="barwrap"><div className={m.profit>=0?"bar pos":"bar neg"} style={{height:`${Math.max(8,Math.abs(m.profit)/max*145)}px`}}></div></div><strong>{m.profit>=0?"+":""}{m.profit.toFixed(0)}</strong><small>{m.k}</small></div>)}</div></section><section className="panel"><div className="panelhead"><div><h2>Recent bets</h2><p>Latest builder activity</p></div><button className="ghost" onClick={()=>setPage("Bet History")}>View all</button></div>{bets.slice(0,5).map(b=><div className="row"><div className={b.result==="Won"?"status win":"status lose"}>{b.result==="Won"?<CheckCircle2 size={17}/>:<TrendingDown size={17}/>}</div><div className="rowmain"><b>{b.bookmaker} · {b.games} games</b><span>{b.selections} selections · {b.odds.toFixed(2)} odds</span></div><strong className={b.return-b.stake>=0?"positive":"negative"}>{b.result==="Pending"?"Pending":(b.return-b.stake>=0?"+":"")+money(b.return-b.stake)}</strong></div>)}</section></div></>}
function AddBet({onAdd,onScan}){return <div className="addgrid"><section className="panel upload"><Upload size={34}/><h2>Scan your bet slip</h2><p>Upload a screenshot and let the scanner extract the builder details.</p><label className="uploadbtn"><Upload size={17}/> Choose screenshot<input type="file" accept="image/*" onChange={onScan}/></label><small>OCR/vision extraction is represented by the demo workflow in this starter build.</small></section><section className="panel form"><h2>Bet details</h2><div className="formgrid">{["Bookmaker","Sport","Date","Stake","Total odds","Potential return","Games","Selections"].map((x,i)=><label>{x}<input defaultValue={i===0?"Bet365":i===1?"Football":i===2?new Date().toISOString().slice(0,10):i===3?"10":i===4?"4.50":i===5?"45.00":i===6?"2":"4"}/></label>)}</div><h3>Markets & selections</h3><div className="chips"><span>Arsenal · Match Result</span><span>Over 2.5 · Goals</span><span>Saka · 1+ SOT</span></div><button className="primary wide" onClick={onAdd}>Save bet</button></section></div>}
function HistoryPage({bets,query,setQuery,month,setMonth,setBets}){return <section className="panel"><div className="filters"><div className="search"><Search size={17}/><input placeholder="Search bets, bookmaker, market..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={month} onChange={e=>setMonth(e.target.value)}><option>All</option>{["2026-09","2026-08"].map(x=><option>{x}</option>)}</select></div><div className="table"><div className="thead"><span>Date</span><span>Bookmaker / sport</span><span>Builder</span><span>Odds</span><span>Stake</span><span>Result</span><span>P/L</span><span></span></div>{bets.map(b=><div className="trow"><span>{b.date}</span><span><b>{b.bookmaker}</b><small>{b.sport}</small></span><span>{b.games} games · {b.selections} selections<small>{b.markets.join(" · ")}</small></span><span>{b.odds.toFixed(2)}</span><span>{money(b.stake)}</span><span><mark className={b.result.toLowerCase()}>{b.result}</mark></span><span className={b.return-b.stake>=0?"positive":"negative"}>{b.result==="Pending"?"—":(b.return-b.stake>=0?"+":"")+money(b.return-b.stake)}</span><button className="iconbtn" onClick={()=>setBets(x=>x.filter(y=>y.id!==b.id))}><Trash2 size={15}/></button></div>)}</div></section>}
function Analytics({stats,bets,months}){let by={};bets.forEach(b=>{by[b.bookmaker]??={stake:0,ret:0,bets:0,wins:0};by[b.bookmaker].stake+=b.stake;by[b.bookmaker].ret+=b.return;by[b.bookmaker].bets++;by[b.bookmaker].wins+=b.result==="Won"?1:0});return <><Cards stats={stats}/><div className="grid2"><section className="panel"><h2>Profit by bookmaker</h2>{Object.entries(by).map(([k,v])=><div className="metricrow"><span>{k}</span><b className={v.ret-v.stake>=0?"positive":"negative"}>{(v.ret-v.stake>=0?"+":"")+money(v.ret-v.stake)}</b></div>)}</section><section className="panel"><h2>Builder size breakdown</h2>{[2,3,4,5,6,8].map(n=>{let a=bets.filter(b=>b.selections===n),p=a.reduce((x,b)=>x+b.return-b.stake,0);return <div className="metricrow"><span>{n} selections</span><span>{a.length} bets</span><b className={p>=0?"positive":"negative"}>{p>=0?"+":""}{money(p)}</b></div>})}</section></div><section className="panel"><h2>Monthly performance</h2><div className="table"><div className="thead"><span>Month</span><span>Bets</span><span>Stake</span><span>Returns</span><span>Profit</span><span>Win rate</span></div>{months.map(m=><div className="trow"><span>{m.k}</span><span>{m.bets}</span><span>{money(m.stake)}</span><span>{money(m.ret)}</span><span className={m.profit>=0?"positive":"negative"}>{m.profit>=0?"+":""}{money(m.profit)}</span><span>{(m.wins/m.bets*100).toFixed(1)}%</span></div>)}</div></section></>}
function SettingsPage(){return <div className="panel settings"><h2>Tracker settings</h2><label>Starting bankroll<input defaultValue="1000"/></label><label>Currency<select><option>GBP (£)</option><option>EUR (€)</option><option>USD ($)</option></select></label><label>Default bookmaker<input defaultValue="Bet365"/></label><p>Production version can persist bets in a database, authenticate users, store slip images, and connect an OCR/vision service for automatic screenshot parsing.</p></div>}
createRoot(document.getElementById("root")).render(<App/>);
